# Generated by Django 4.2 on 2023-05-22 16:43

import app_profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_profile.models.avatar_preview_directory_path,
                        verbose_name="аватар",
                    ),
                ),
                ("alt", models.CharField(max_length=30, verbose_name="инфо картинки")),
            ],
            options={
                "verbose_name": "image avatar",
                "verbose_name_plural": "images avatar",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullName", models.CharField(max_length=30, verbose_name="ФИО")),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="эл. почта"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="телефон"
                    ),
                ),
                (
                    "avatar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_profile.imageprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profile",
            },
        ),
    ]
