# Generated by Django 4.2 on 2023-05-22 16:43

import app_shop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="категория")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "category",
            },
        ),
        migrations.CreateModel(
            name="ImageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=app_shop.models.category_preview_directory_path,
                        verbose_name="картинка",
                    ),
                ),
                ("alt", models.CharField(max_length=30, verbose_name="инфо картинки")),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=1000000,
                        verbose_name="цена",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="количество"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=128, verbose_name="название товара"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="описание товара"
                    ),
                ),
                (
                    "fullDescription",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="полное описание"
                    ),
                ),
                (
                    "freeDelivery",
                    models.BooleanField(default=True, verbose_name="категория активна"),
                ),
                ("reviews", models.IntegerField(default=0, verbose_name="отзыв")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        verbose_name="рейтинг",
                    ),
                ),
                (
                    "sold_amount",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="количество проданного товара"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product",
                        to="app_shop.category",
                        verbose_name="категория товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "db_table": "product",
                "ordering": ["-sold_amount"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tags",
                        to="app_shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table": "specification_names",
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="подкатегория")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_shop.imagecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategory",
            },
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Название")),
                ("value", models.CharField(max_length=32, verbose_name="Значение")),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specifications",
                        to="app_shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "specification",
                "verbose_name_plural": "specifications",
                "db_table": "specifications",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=1000000,
                        verbose_name="цена",
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=1000000,
                        verbose_name="цена со скидкой",
                    ),
                ),
                (
                    "dateFrom",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="дата начала"
                    ),
                ),
                (
                    "dateTo",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="дата конца"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Заголовок")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="продукт",
                        to="app_shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "sale",
                "verbose_name_plural": "sales",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=25, null=True, verbose_name="Автор"),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                (
                    "text",
                    models.TextField(
                        max_length=255, null=True, verbose_name="Содержание"
                    ),
                ),
                (
                    "rate",
                    models.FloatField(default=0, null=True, verbose_name="Рейтинг"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review",
                        to="app_shop.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_profile.profile",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "reviews",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="ImageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "src",
                    models.ImageField(
                        upload_to="image_product/", verbose_name="изображение"
                    ),
                ),
                ("alt", models.CharField(default="string", max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="app_shop.product",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="images",
                        to="app_shop.sales",
                    ),
                ),
            ],
            options={
                "verbose_name": "imageProduct",
                "verbose_name_plural": "ImageProducts",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="app_shop.imagecategory"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="category", to="app_shop.subcategory"
            ),
        ),
        migrations.CreateModel(
            name="Basket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=1000000,
                        verbose_name="цена",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="количество"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product",
                        to="app_shop.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "basket",
                "verbose_name_plural": "baskets",
                "ordering": ["-product"],
            },
        ),
    ]
