# Generated by Django 4.2 on 2023-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="dateFrom",
            field=models.DateField(blank=True, null=True, verbose_name="дата начала"),
        ),
        migrations.AlterField(
            model_name="sales",
            name="dateTo",
            field=models.DateField(blank=True, null=True, verbose_name="дата конца"),
        ),
    ]
