# Generated by Django 4.2 on 2023-05-23 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0002_alter_sales_datefrom_alter_sales_dateto"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Basket",
        ),
    ]
