# Generated by Django 4.2 on 2023-05-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0003_delete_basket"),
        ("app_order", "0003_alter_order_paymenttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.CharField(
                default=None, max_length=50, null=True, verbose_name="эл.почта"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fullName",
            field=models.CharField(
                default=None, max_length=120, null=True, verbose_name="ФИО"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="phone",
            field=models.CharField(
                default=None, max_length=20, null=True, verbose_name="телефон"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(
                related_name="products", to="app_shop.product", verbose_name="продукты"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                default="free", max_length=120, verbose_name="Доставка"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.ForeignKey(
                default="online",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentType",
                to="app_order.payment",
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="checkout", max_length=20, verbose_name="Статус"
            ),
        ),
    ]
