# Generated by Django 4.2 on 2023-05-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app_order",
            "0004_order_email_order_fullname_order_phone_order_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                default="online", max_length=50, null=True, verbose_name="Способ оплаты"
            ),
        ),
    ]
