# Generated by Django 4.2 on 2023-05-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_shop", "0003_delete_basket"),
        ("app_order", "0005_alter_order_paymenttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basket",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="order_product",
                to="app_shop.product",
                verbose_name="продукты",
            ),
        ),
    ]
