# Generated by Django 4.2 on 2023-05-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_profile", "0001_initial"),
        ("app_order", "0006_remove_basket_order_remove_order_product_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "оплата", "verbose_name_plural": "оплаты"},
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_profile.profile",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="name",
            field=models.CharField(
                default=1, max_length=20, verbose_name="Имя владельца"
            ),
            preserve_default=False,
        ),
    ]
